#!/usr/bin/env perl

# BerylDB - A modular database.
# http://www.beryldb.com
#
# Copyright (C) 2021 Carlos F. Ferry <cferry@beryldb.com>
# 
# This file is part of BerylDB. BerylDB is free software: you can
# redistribute it and/or modify it under the terms of the BSD License
# version 3.
#
# More information about our licensing can be found at https://docs.beryl.dev

use v5.10.0;
use strict;
use warnings FATAL => qw(all);

use File::Basename qw(dirname);
use FindBin        qw($RealDir);

use lib dirname $RealDir;
use make::utils;
use make::configure;

$ENV{DEBUG} = 3;
$ENV{VERBOSE} = 1;

execute 'git', 'clean', '-dfx';

my $root = dirname $RealDir;
my @compilers = $#ARGV >= 0 ? @ARGV : qw(g++ c++ clang++);

for my $compiler (@compilers) 
{
        if (system "$compiler -v > /dev/null 2>&1") 
	{
                say "$compiler not installed.";
                next;
        }

        $ENV{CXX} = $compiler;

        my @cflags;

        if (execute "$root/configure", '--development', @cflags) 
        {
                say "Unable to configure using the $compiler compiler.";
                exit 1;
        }
        
        if (execute 'make', '--directory', $root, '--jobs', get_cpu_count() + 1, 'install') 
        {	
                say "Unable to compile using the $compiler compiler.";
                exit 1;
        }

        say "Building using the $compiler compiler.";
}



